services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql-task-flow
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      #MYSQL_USER: "root"
    ports:
      # Mapeia a porta 3306 do container para a porta 3306 do seu host (máquina)
      - "3306:3306"
    volumes:
      # (Opcional) Persistência de dados: mapeia o diretório de dados do MySQL
      # para um volume nomeado, garantindo que seus dados não sejam perdidos
      # se o container for removido.
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: # Define o volume nomeado para a persistência dos dados
